[package]
name = "verifier"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
num-bigint = "0.4"
num-traits = "0.2"

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
